name: pantrywise
description: PantryWise - Smart Grocery & Expense Manager
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.7
  supabase_flutter: ^2.5.0
  http: ^1.2.2
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.12.0
  mobile_scanner: ^6.0.2
  pdf: ^3.11.0
  printing: ^5.13.3
  provider: ^6.1.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
