name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print repo tree (debug)
        run: |
          pwd
          ls -la
          if [ -f pubspec.yaml ]; then echo "pubspec found"; else echo "pubspec MISSING" && exit 1; fi

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          cache: true

      # Scaffold android/ios if missing (safe even if they exist)
      - name: Scaffold platforms if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
          flutter --version

      - name: Flutter pub get
        run: flutter pub get

      # Generate i18n only if l10n.yaml exists
      - name: Generate localizations (if configured)
        run: |
          if [ -f "l10n.yaml" ]; then
            if [ ! -d "lib/l10n" ]; then
              mkdir -p lib/l10n
              cat > lib/l10n/app_en.arb <<'EOF'
              {
                "@@locale": "en",
                "appTitle": "PantryWise"
              }
              EOF
            fi
            flutter gen-l10n
          else
            echo "No l10n.yaml; skipping gen-l10n"
          fi

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build release APK
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: >
          flutter build apk --release
          --dart-define=SUPABASE_URL=${SUPABASE_URL:-}
          --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
          -v

      - name: Upload APK artifact (if present)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pantrywise-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Always upload useful logs to help debugging if it fails
      - name: Upload Gradle/Flutter logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/
            .dart_tool/
            **/build.gradle
            **/gradle.properties
            **/flutter.gradle
            **/*.log
          if-no-files-found: ignore
