name: Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          cache: true

      # Ensures android/ios folders exist even if not committed
      - name: Scaffold platforms if missing
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Flutter pub get
        run: flutter pub get

      # Generate localizations only if l10n.yaml exists
      - name: Generate localizations (if configured)
        run: |
          if [ -f "l10n.yaml" ]; then
            flutter gen-l10n
          else
            echo "No l10n.yaml; skipping gen-l10n"
          fi

      - name: Build release APK
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: >
          flutter build apk --release
          --dart-define=SUPABASE_URL=${SUPABASE_URL}
          --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: pantrywise-apk
          path: build/app/outputs/flutter-apk/app-release.apk
